FROM yankovg/python3.8.2-ubuntu18.04

# USER root

RUN apt-get -qq update && apt-get -qq -y install \
    vim zsh dash csh tcsh posh ksh fish git libbz2-dev \
    patch libmagic1 openjdk-8-jdk \
    curl gnupg apt-transport-https \
    &&  rm -rf /var/lib/apt/lists/* /var/log/dpkg.log

ENV PYTHON_VERSION 3.8


# conda and test dependencies
RUN curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /opt/conda/ \
    && rm -rf /tmp/miniconda.sh \
    && /opt/conda/bin/conda install -y -c conda-canary -c defaults -c conda-forge \
    conda conda-package-handling \
    python=$PYTHON_VERSION pycosat requests ruamel_yaml cytoolz \
    anaconda-client nbformat \
    pytest pytest-cov pytest-timeout mock responses pexpect xonsh \
    flake8 \
    && /opt/conda/bin/conda clean --all --yes

RUN /opt/conda/bin/pip install codecov radon \
    && rm -rf ~root/.cache/pip


# conda-build and test dependencies
RUN /opt/conda/bin/conda install -y -c defaults -c conda-forge \
    conda-build patch git \
    perl pytest-xdist pytest-catchlog pytest-mock \
    anaconda-client \
    filelock jinja2 conda-verify pkginfo \
    glob2 beautifulsoup4 chardet pycrypto \
    && /opt/conda/bin/conda clean --all --yes

RUN curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc \
    && chmod +x $HOME/minio-binaries/mc && export PATH=$PATH:$HOME/minio-binaries/

RUN apt-get update && apt-get install wget iputils-ping -y

ENV PATH="/opt/conda/bin:$PATH"
ENV PATH="$PATH:$HOME/minio-binaries/"

COPY ./requirements.txt /srv/requirements.txt

RUN python3.8 -m pip install -r /srv/requirements.txt

RUN python3.8 -m pip install jupyterlab

RUN mkdir /srv/notebooks

WORKDIR /srv/notebooks

CMD ["jupyter", "lab", "--ip", "0.0.0.0", "--port", "9999", "--no-browser", "--allow-root", "--NotebookApp.token=research"]


# docker build -t jnotebook_image -f Dockerfile_jnotebook .